# ./docker-compose.yml
version: '3.8'

services:
  web:
    # image: dunglas/frankenphp:alpine
    build: .
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
#      - /etc/php:/usr/local/etc/php/conf.d
    ports:
      - "80:80"
      - "443:443"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  caddy_data:
  caddy_config:
  db_data:
    driver: local


